## Those Exclusions are to prevent file access on public links for sharing and downloading, along with being prevented to use the web file editor which is falsely flagged by modsec.

SecAction \
    "id:900221,\
    phase:1,\
    pass,\
    t:none,\
    nolog,\
    setvar:'tx.allowed_request_content_type=|application/x-www-form-urlencoded| |multipart/form-data| |text/xml| |application/xml| |application/soap+xml| |application/json| |application/offset+octet-stream| |application/octet-stream| |text/plain|'"

SecRule REQUEST_FILENAME "@rx ^/api/files/(save|cat)$" \
    "id:1001001,\
    phase:1,\
    pass,\
    nolog,\
    t:none,\
    ctl:ruleRemoveById=920420"
